x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  eigenda-proxy:
    image: ${EIGENDA_DOCKER_REPO}:${EIGENDA_DOCKER_TAG}
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-eigenda-proxy.sh
    environment:
      - EIGENDA_LOCAL_DISPERSER_RPC=${EIGENDA_LOCAL_DISPERSER_RPC}
      - EIGENDA_LOCAL_SVC_MANAGER_ADDR=${EIGENDA_LOCAL_SVC_MANAGER_ADDR}
      - OP_NODE__RPC_ENDPOINT=${L1_RPC}
    volumes:
      - eigenda-data:/data
      - ./eigenda/docker-entrypoint.sh/:/scripts/start-eigenda-proxy.sh
    <<: *logging

volumes:
  eigenda-data:
