x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  op-geth-init:
    profiles: [ "geth" ]
    restart: "no"
    build:
      context: ./init
      dockerfile: Dockerfile
    image: init:optimism
    pull_policy: never
    environment:
      - SNAPSHOT=${SNAPSHOT:-}
      - SNAPSHOT_PART=${SNAPSHOT_PART:-}
    volumes:
      - opgeth-data:/var/lib/op-geth
      - jwtsecret:/var/lib/op-geth/ee-secret
      - /etc/localtime:/etc/localtime:ro
  op-geth:
    profiles: [ "geth" ]
    restart: "unless-stopped"
    build:
      context: ./op-geth
      dockerfile: ${OPGETH_DOCKERFILE:-Dockerfile.binary}
      args:
        - DOCKER_TAG=${OPGETH_DOCKER_TAG}
        - DOCKER_REPO=${OPGETH_DOCKER_REPO}
    image: op-geth:${NETWORK}
    pull_policy: never
    stop_grace_period: 5m
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NETWORK=${NETWORK:-}
      - LEGACY=${LEGACY:-false}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - EL_INIT_EXTRAS=${EL_INIT_EXTRAS:-}
      - OPGETH_P2P_BOOTNODES=${OPGETH_P2P_BOOTNODES}
      - OPGETH_P2P_TRUSTED_NODES=${OPGETH_P2P_TRUSTED_NODES}
      - GENESIS_URL=${GENESIS_URL:-}
      - NETWORK=${NETWORK}
      - SEQUENCER=${SEQUENCER:-}
      - ROLLUP_HALT=${ROLLUP_HALT}
      - INIT_STATE_SCHEME=${INIT_STATE_SCHEME:-path}
    volumes:
      - opgeth-data:/var/lib/op-geth
      - jwtsecret:/var/lib/op-geth/ee-secret
      - /etc/localtime:/etc/localtime:ro
      - ./private-config:/tmp/private-config:ro
    ports:
      - ${OPGETH_P2P_PORT:-30303}:${OPGETH_P2P_PORT:-30303}/tcp
      - ${OPGETH_P2P_PORT:-30303}:${OPGETH_P2P_PORT:-30303}/udp
    networks:
      default:
        aliases:
          - ${NETWORK}-geth # This allows multiple Optimism Docker stacks all connected to the same central traefik
    depends_on:
      op-geth-init:
        condition: service_completed_successfully
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --datadir
      - /var/lib/op-geth
      - --rollup.disabletxpoolgossip=${DISABLE_TXPOOL_GOSSIP:-true}
      - --port
      - ${OPGETH_P2P_PORT:-30303}
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - "8551"
      - --authrpc.jwtsecret
      - /var/lib/op-geth/ee-secret/jwtsecret
      - --authrpc.vhosts=*
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${RPC_PORT:-8545}
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${WS_PORT:-8546}
      - --ws.origins=*
      - --metrics
      - --pprof
      - --pprof.addr
      - 0.0.0.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST:-op}.service=${RPC_HOST:-op}
      - traefik.http.routers.${RPC_HOST:-op}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-op}.rule=Host(`${RPC_HOST:-op}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-op}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-op}lb.service=${RPC_HOST:-op}
      - traefik.http.routers.${RPC_HOST:-op}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-op}lb.rule=Host(`${RPC_LB:-op-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-op}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-op}.loadbalancer.server.port=${RPC_PORT:-8545}
      - traefik.http.routers.${WS_HOST:-opws}.service=${WS_HOST:-opws}
      - traefik.http.routers.${WS_HOST:-opws}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-opws}.rule=Host(`${WS_HOST:-opws}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-opws}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-opws}lb.service=${WS_HOST:-opws}
      - traefik.http.routers.${WS_HOST:-opws}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-opws}lb.rule=Host(`${WS_LB:-opws-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-opws}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-opws}.loadbalancer.server.port=${WS_PORT:-8546}
      - metrics.scrape=true
      - metrics.path=/debug/metrics/prometheus
      - metrics.port=6060
      - metrics.network=${NETWORK:-}

  op-reth-init:
    profiles: ["reth"]
    restart: "no"
    build:
      context: ./init-reth
      dockerfile: Dockerfile
    image: init:optimism-reth
    pull_policy: never
    environment:
      - SNAPSHOT=${SNAPSHOT:-}
      - SNAPSHOT_PART=${SNAPSHOT_PART:-}
    volumes:
      - opreth-data:/var/lib/op-reth
      - jwtsecret:/var/lib/op-reth/ee-secret
      - /etc/localtime:/etc/localtime:ro
  op-reth:
    profiles: [ "reth" ]
    restart: unless-stopped
    build:
      context: ./op-reth
      dockerfile: ${OPRETH_DOCKERFILE:-Dockerfile.binary}
      args:
        - DOCKER_TAG=${OPRETH_DOCKER_TAG}
        - DOCKER_REPO=${OPRETH_DOCKER_REPO}
    image: op-reth:${NETWORK}
    pull_policy: never
    stop_grace_period: 5m
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NETWORK=${NETWORK:-}
      - LEGACY=${LEGACY:-false}
      - EL_RETH_EXTRAS=${EL_RETH_EXTRAS:-}
      - EL_RETH_INIT_EXTRAS=${EL_RETH_INIT_EXTRAS:-}
      - OPRETH_P2P_BOOTNODES=${OPRETH_P2P_BOOTNODES}
      - OPRETH_P2P_TRUSTED_NODES=${OPRETH_P2P_TRUSTED_NODES}
      - GENESIS_URL=${GENESIS_URL:-}
      - NETWORK=${NETWORK}
      - SEQUENCER=${SEQUENCER:-}
      - ROLLUP_HALT=${ROLLUP_HALT}
      - INIT_STATE_SCHEME=${INIT_STATE_SCHEME:-path}
    volumes:
      - opreth-data:/var/lib/op-reth
      - jwtsecret:/var/lib/op-reth/ee-secret
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${OPRETH_P2P_PORT:-30304}:${OPRETH_P2P_PORT:-30304}/tcp
      - ${OPRETH_P2P_PORT:-30304}:${OPRETH_P2P_PORT:-30304}/udp
    networks:
      default:
        aliases:
          - ${NETWORK}-reth
    depends_on:
      op-reth-init:
        condition: service_completed_successfully
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - op-reth
      - node
      - --datadir
      - /var/lib/op-reth
      - --chain
      - ${OPRETH_CHAIN}
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${RPC_PORT:-8545}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${WS_PORT:-8546}
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - "8551"
      - --authrpc.jwtsecret
      - /var/lib/op-reth/ee-secret/jwtsecret
      - --port
      - ${OPRETH_P2P_PORT:-30304}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST:-op}.service=${RPC_HOST:-op}
      - traefik.http.routers.${RPC_HOST:-op}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-op}.rule=Host(`${RPC_HOST:-op}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-op}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-op}lb.service=${RPC_HOST:-op}
      - traefik.http.routers.${RPC_HOST:-op}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-op}lb.rule=Host(`${RPC_LB:-op-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-op}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-op}.loadbalancer.server.port=${RPC_PORT:-8545}
      - traefik.http.routers.${WS_HOST:-opws}.service=${WS_HOST:-opws}
      - traefik.http.routers.${WS_HOST:-opws}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-opws}.rule=Host(`${WS_HOST:-opws}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-opws}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-opws}lb.service=${WS_HOST:-opws}
      - traefik.http.routers.${WS_HOST:-opws}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-opws}lb.rule=Host(`${WS_LB:-opws-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-opws}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-opws}.loadbalancer.server.port=${WS_PORT:-8546}
      - metrics.scrape=true
      - metrics.network=${NETWORK:-}

  op-node:
    restart: "unless-stopped"
    build:
      context: ./op-node
      dockerfile: ${OPNODE_DOCKERFILE:-Dockerfile.binary}
      args:
        - DOCKER_TAG=${OPNODE_DOCKER_TAG}
        - DOCKER_REPO=${OPNODE_DOCKER_REPO}
        - ORIGINAL_USER=${OPNODE_ORIGINAL_USER:-root}
    image: op-node:${NETWORK}
    pull_policy: never
    stop_grace_period: 1m
    stop_signal: SIGHUP
    environment:
      - CL_EXTRAS=${CL_EXTRAS}
      - OPNODE_P2P_BOOTNODES=${OPNODE_P2P_BOOTNODES}
      - OPNODE_P2P_STATIC_PEERS=${OPNODE_P2P_STATIC_PEERS}
      - ROLLUP_URL=${ROLLUP_URL:-}
      - NETWORK=${NETWORK}
      - ROLLUP_HALT=${ROLLUP_HALT}
      - OPNODE_SYNC_MODE=${OPNODE_SYNC_MODE}
      - L1_BEACON=${L1_BEACON}
    volumes:
      - jwtsecret:/var/lib/op-node/ee-secret
      - opnode-data:/var/lib/op-node
      - /etc/localtime:/etc/localtime:ro
      - ./private-config:/tmp/private-config:ro
    ports:
      - ${OPNODE_P2P_PORT:-9222}:${OPNODE_P2P_PORT:-9222}/tcp
      - ${OPNODE_P2P_PORT:-9222}:${OPNODE_P2P_PORT:-9222}/udp
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - ${OPNODE_BIN_PATH:-op-node}
      - --log.level
      - ${LOG_LEVEL}
      - --l2
      - ${L2_CONNECTION_KIND:-http}://${NETWORK}:8551
      - --l2.jwt-secret
      - /var/lib/op-node/ee-secret/jwtsecret
      - --l1
      - ${L1_RPC}
      - --l1.rpckind
      - ${L1_RPC_KIND:-basic}
      - --rpc.addr
      - 0.0.0.0
      - --rpc.port
      - ${OPNODE_RPC_PORT:-9545}
      - --metrics.enabled
      - --p2p.listen.tcp
      - ${OPNODE_P2P_PORT:-9222}
      - --p2p.discovery.path
      - /var/lib/op-node/opnode_discovery_db
      - --p2p.peerstore.path
      - /var/lib/op-node/opnode_peerstore_db
      - --p2p.priv.path
      - /var/lib/op-node/opnode_p2p_priv.txt
    labels:
      - traefik.enable=true
      - traefik.http.routers.${OPNODE_HOST:-opnode}.service=${OPNODE_HOST:-opnode}
      - traefik.http.routers.${OPNODE_HOST:-opnode}.entrypoints=websecure
      - traefik.http.routers.${OPNODE_HOST:-opnode}.rule=Host(`${OPNODE_HOST:-opnode}.${DOMAIN}`)
      - traefik.http.routers.${OPNODE_HOST:-opnode}.tls.certresolver=letsencrypt
      - traefik.http.routers.${OPNODE_HOST:-opnode}lb.service=${OPNODE_HOST:-opnode}
      - traefik.http.routers.${OPNODE_HOST:-opnode}lb.entrypoints=websecure
      - traefik.http.routers.${OPNODE_HOST:-opnode}lb.rule=Host(`${OPNODE_LB:-opnode-lb}.${DOMAIN}`)
      - traefik.http.routers.${OPNODE_HOST:-opnode}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${OPNODE_HOST:-opnode}.loadbalancer.server.port=${OPNODE_RPC_PORT:-9545}
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=7300
      - metrics.network=${NETWORK:-}
#    depends_on:
#      op-geth:
#        condition: service_started
#      op-reth:
#        condition: service_started

volumes:
  opgeth-data:
  opnode-data:
  jwtsecret:
  opreth-data:

