x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  prom-metrics:
    image: prom-metrics
    build:
      context: ./prom-metrics
    restart: unless-stopped
    pull_policy: never
    environment:
      - NETWORK=${NETWORK:-}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8000
    # ports:
    #   - 8000:8000/tcp
    <<: *logging

