ARG DOCKER_TAG

FROM ethereumoptimism/l2geth:${DOCKER_TAG}

RUN apk update && apk add --no-cache ca-certificates tzdata bash su-exec

RUN mkdir -p /var/lib/l2geth

# Cannot assume buildkit, hence no chmod
COPY ./docker-entrypoint.sh /usr/local/bin/
# Belt and suspenders
RUN chmod -R 755 /usr/local/bin/*

ENTRYPOINT ["geth"]
