ARG DOCKER_TAG=latest
ARG DOCKER_REPO=us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node

FROM ${DOCKER_REPO}:${DOCKER_TAG}

RUN apt update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y ca-certificates tzdata bash curl gosu && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/lib/op-node/ee-secret

# Cannot assume buildkit, hence no chmod
COPY ./docker-entrypoint.sh /usr/local/bin/
# Belt and suspenders
RUN chmod -R 755 /usr/local/bin/*

ENTRYPOINT ["op-node"]
